version: '2'
services:
  magento:
    hostname: magento
    container_name: magento
    build: .
    image: magento
    ports:
      - "8080:8080"
    user: "100000"
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      MYSQL_USER: magento
      MYSQL_PASSWORD: magento
      MYSQL_DATABASE: magento
      MYSQL_ROOT_PASSWORD: magento

  mysql:
    hostname: mysql
    container_name: mysql
    image: 1and1internet/ubuntu-16-nginx-1.10.0-php-7.0-phpmyadmin-4.6-mysql-5.7:unstable
    ports:
      - "3306:3306"
      - "8081:8080"
    user: "100000"
    environment:
      MYSQL_USER: magento
      MYSQL_PASSWORD: magento
      MYSQL_DATABASE: magento
      MYSQL_ROOT_PASSWORD: magento
