version: '2'
services:
  magento:
    hostname: magento
    container_name: magento
    build: .
    image: magento
    ports:
      - "8080:8080"
    user: "100000"
    depends_on:
      - mysql
    links:
      - mysql
    environment:
      MYSQL_USER: magento
      MYSQL_PASSWORD: magento
      MYSQL_DATABASE: magento
      MYSQL_ROOT_PASSWORD: magento

  mysql:
    hostname: mysql
    container_name: mysql
    image: mariadb:10.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: magento
      MYSQL_PASSWORD: magento
      MYSQL_DATABASE: magento
      MYSQL_ROOT_PASSWORD: magento



