apiVersion: v1
kind: Template
metadata:
  annotations:
    description: Ephemeral WordPress content management system (CMS)
  name: 1and1-magento-apache-mysql-ephemeral
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      description: Definition for Deploying Magento database.
    labels:
      service: mysql
    name: ${DATABASE_SERVICE_NAME}
  spec:
    replicas: 1
    selector:
      name: ${DATABASE_SERVICE_NAME}
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          name: ${DATABASE_SERVICE_NAME}
          service: mysql
        name: ${DATABASE_SERVICE_NAME}
      spec:
        containers:
        - env:
          - name: MYSQL_DATABASE
            value: ${MAGENTO_DB_NAME}
          - name: MYSQL_PASSWORD
            value: ${MAGENTO_DB_PASSWORD}
          - name: MYSQL_ROOT_PASSWORD
            value: ${DATABASE_ADMIN_PASSWORD}
          - name: MYSQL_USER
            value: ${MAGENTO_DB_USER}
          image: 1and1internet/ubuntu-16-nginx-1.10.0-php-7.0-phpmyadmin-4.6-mysql-5.7:latest
          imagePullPolicy: Always
          name: ${DATABASE_SERVICE_NAME}
          ports:
          - containerPort: 3306
            protocol: TCP
          - containerPort: 8080
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -i
              - -c
              - MYSQL_PWD="$MYSQL_PASSWORD" mysql -h 127.0.0.1 -u $MYSQL_USER -D $MYSQL_DATABASE
                -e 'SELECT 1'
            initialDelaySeconds: 5
            timeoutSeconds: 1
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /var/lib/mysql
            name: ${DATABASE_SERVICE_NAME}-data
        restartPolicy: Always
        securityContext:
          runAsUser: ${OPENSHIFT_USER}
        volumes:
        - emptyDir:
            medium: ""
          name: ${DATABASE_SERVICE_NAME}-data
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      description: Definition for deploying Magento
    labels:
      service: magento-apache
    name: ${APP_SERVICE_NAME}
  spec:
    replicas: 1
    selector:
      name: ${APP_SERVICE_NAME}
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          name: ${APP_SERVICE_NAME}
          service: magento-apache
        name: ${APP_SERVICE_NAME}}
      spec:
        containers:
        - env:
          - name: MYSQL_HOST
            value: ${DATABASE_SERVICE_NAME}
          - name: MYSQL_DATABASE
            value: ${MAGENTO_DB_NAME}
          - name: MYSQL_USER
            value: ${MAGENTO_DB_USER}
          - name: MYSQL_PASSWORD
            value: ${MAGENTO_DB_PASSWORD}
          image: 1and1internet/ubuntu-16-apache-2.4-php-5.6-magento2.0:latest
          imagePullPolicy: Always
          name: ${APP_SERVICE_NAME}
          ports:
          - containerPort: 8080
            protocol: TCP
          volumeMounts:
          - mountPath: /var/www/html
            name: magento-data
        restartPolicy: Always
        securityContext:
          runAsUser: ${OPENSHIFT_USER}
        volumes:
        - emptyDir:
            medium: ""
          name: magento-data
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: Route
  metadata:
    name: ${APP_SERVICE_NAME}
  spec:
    host: ${APPLICATION_DOMAIN}
    port:
      targetPort: 8080
      protocol: TCP
    to:
      kind: Service
      name: ${APP_SERVICE_NAME}
- apiVersion: v1
  kind: Route
  metadata:
    name: ${DATABASE_SERVICE_NAME}
  spec:
    host: ${DATABASE_ADMIN_DOMAIN}
    port:
      targetPort: 8080
      protocol: TCP
    to:
      kind: Service
      name: ${DATABASE_SERVICE_NAME}
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      service: mysql
    name: ${DATABASE_SERVICE_NAME}
  spec:
    ports:
    - name: ${DATABASE_SERVICE_NAME}
      port: 3306
      protocol: TCP
      targetPort: 3306
    - name: ${DATABASE_SERVICE_NAME}-phpmyadmin
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      name: ${DATABASE_SERVICE_NAME}
    sessionAffinity: None
    type: ClusterIP
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      service: magento
    name: ${APP_SERVICE_NAME}  
  spec:
    ports:
    - name: ${APP_SERVICE_NAME}  
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      name: ${APP_SERVICE_NAME}
    sessionAffinity: None
    type: ClusterIP
parameters:
- description: Application service name
  displayName: Application service name
  from: magento[0-9]{3}
  generate: expression
  name: APP_SERVICE_NAME
  required: true
- description: Database service name
  displayName: Database service name
  from: mysql[0-9]{3}
  generate: expression
  name: DATABASE_SERVICE_NAME
  required: true
- description: Magento default URL
  displayname: Website URL
  name: APPLICATION_DOMAIN
  required: true
- description: Magento Database Name
  displayname: Magento Database Name
  name: MAGENTO_DB_NAME
  from: magentodb[0-9]{3}
  generate: expression
  required: true
- description: Magento Database User
  displayname: Magento Database User
  name: MAGENTO_DB_USER
  from: wp-db-user[0-9]{3}
  generate: expression
  required: true
- description: Magento Database Password
  displayname: Magento Database Password
  from: '[a-zA-Z0-9]{24}'
  generate: expression
  name: MAGENTO_DB_PASSWORD
  required: true
- description: Password for the database admin user which you can use to administer
    the database
  displayName: Database administrator password
  from: '[a-zA-Z0-9]{16}'
  generate: expression
  name: DATABASE_ADMIN_PASSWORD
  required: true
- description: Openshift user
  dislayName: Openshift user
  name: OPENSHIFT_USER
  required: true
- description: Database Admin URL
  displayname: Database Admin URL
  name: DATABASE_ADMIN_DOMAIN
  required: true
